image: python:3.8

pipelines:
  branches:
    master:
      - step:
          name: Test and lint
          caches:
            - "pip"
          script:
            - apt-get update && apt-get install -y make
            - pip install poetry
            - poetry install
            - make lint
            - make isort
            - make test
          artifacts:
            - htmlcov/**

  pull-requests:
    "**":
      - step:
          name: Test and lint
          caches:
            - "pip"
          script:
            - apt-get update && apt-get install -y make
            - pip install poetry
            - poetry install
            - make lint
            - make isort
            - make test
  tags:
    "v*.*.*":
      - step:
          name: Test and lint
          caches:
            - "pip"
          script:
            - apt-get update && apt-get install -y make
            - pip install poetry
            - poetry install
            - make lint
            - make isort
            - make test
      - step:
          name: Deploy
          caches:
            - "pip"
          script:
            - pip install poetry
            - echo "$GOOGLE_SERVICE_ACCOUNT_CREDENTIALS" | base64 -d > credentials.json
            - gcloud auth activate-service-account bitbucket-pipelines@ms--tiber-com-lib--pro--8bd7.iam.gserviceaccount.com --key-file=credentials.json --project=ms--tiber-com-lib--pro--8bd7 --project ms--tiber-com-lib--pro--8bd7
            - poetry self add keyrings.google-artifactregistry-auth
            - poetry build
            - poetry publish -r syscorp-librarian 
