apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.project_name}}
  description: {{cookiecutter.project_description}}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - tiber
spec:
  type: service
  lifecycle: development
  owner: tiber-team
